<?php

namespace Hiberus\Curso\Console;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Input\InputOption;


class AuthorsCommand extends Command
{
    const NAME = 'name';
    protected \Hiberus\Curso\Model\Author $author;

    public function __construct(
        \Hiberus\Curso\Model\Author $author,
        string $name = null
    )
    {
        $this->author = $author;
        parent::__construct($name);
    }

    protected function configure()
    {
        $this->setName('hiberus:authors:show')
            ->setDescription('Mostrar autores')
            ->addOption(
                self::NAME,
                null,
                InputOption::VALUE_REQUIRED,
                'Name'
            );
        parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        if ($name = $input->getOption(self::NAME)) {
            $output->writeln('<info>Provided name is `' . $name . '`</info>');
        }
        else{
            $name=$this->author->getAuthorName();
        }
        $output->writeln('<info>Mi autor favorito es '. $name.'</info>');
        // parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}
